{% set name = "pz-rail-base" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pz_rail_base-{{ version }}.tar.gz
  sha256: cba9b498dbfe864d507adbd5589d4530a6c25a26f33dee43cf2e72b6aadef0aa

build:
  entry_points:
    - rail = rail.cli.rail.commands:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - deprecated
    - pyyaml
    - numpy
    - click
    - lsstdesc-ceci >=2.0.1
    - qp-prob >=0.9.2
    - scipy >=1.9.0

test:
  imports:
    - rail.core
  commands:
    - pip check
    - rail --help
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: http://github.com/LSSTDESC/rail_base
  summary: Base classes and core code for Redshift Assessment Infrastructure Layers
  description: |
    RAIL is a flexible software library providing tools to produce at-scale photometric redshift data products, including uncertainties and summary statistics, and stress-test them under realistically complex systematics.

extra:
  recipe-maintainers:
    - sschmidt23
    - eacharles
